"""Regression tests generated from real device logs.

Generated by:  python tools/generate_tests_from_log.py
DO NOT EDIT – re-run the generator to refresh.

Each test replays the exact BLE notification bytes captured from a physical
device and asserts the field values produced by the CURRENT parser.
"""
from __future__ import annotations

from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from custom_components.oclean_ble.coordinator import OcleanCoordinator
from tests.simulator import OcleanDeviceSimulator


# ---------------------------------------------------------------------------
# Helpers (mirrors tests/test_simulator.py)
# ---------------------------------------------------------------------------

def _make_hass():
    hass = MagicMock()
    hass.data = {}
    return hass


def _make_coordinator(mac: str = "AA:BB:CC:DD:EE:FF") -> OcleanCoordinator:
    coord = OcleanCoordinator(_make_hass(), mac, "Oclean", 300)
    coord._store_loaded = True
    return coord


def _make_service_info(mac: str = "AA:BB:CC:DD:EE:FF"):
    device = MagicMock()
    device.address = mac
    si = MagicMock()
    si.device = device
    return si


async def _run_poll(coordinator: OcleanCoordinator, client: AsyncMock) -> dict:
    with patch("custom_components.oclean_ble.coordinator.bluetooth") as bt_mock, \
         patch(
             "custom_components.oclean_ble.coordinator.establish_connection",
             new_callable=AsyncMock,
             return_value=client,
         ), \
         patch(
             "custom_components.oclean_ble.coordinator.asyncio.sleep",
             new_callable=AsyncMock,
         ), \
         patch.object(coordinator, "_paginate_sessions", new_callable=AsyncMock), \
         patch.object(coordinator, "_import_new_sessions", new_callable=AsyncMock):
        bt_mock.async_last_service_info.return_value = _make_service_info(coordinator._mac)
        return await coordinator._poll_device()


class TestGenerated_unknown:
    """Auto-generated regression tests for unknown.

    26 unique poll pattern(s) captured from real device.
    """

    @pytest.mark.asyncio
    async def test_20260224_2112_batt54_1sess_000(self):
        """Poll 2026-02-24 21:12:42 – battery=54, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(54)
            .add_notification(bytes.fromhex('0303020ed5360000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 54
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2113_batt54_1sess_001(self):
        """Poll 2026-02-24 21:13:45 – battery=54, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(54)
            .add_notification(bytes.fromhex('0303020ed4360000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 54
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2114_batt54_1sess_002(self):
        """Poll 2026-02-24 21:14:48 – battery=54, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(54)
            .add_notification(bytes.fromhex('0303020ed7360000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 54
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2116_batt54_1sess_003(self):
        """Poll 2026-02-24 21:16:55 – battery=54, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(54)
            .add_notification(bytes.fromhex('0303020ed3360000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 54
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2118_batt53_1sess_004(self):
        """Poll 2026-02-24 21:18:00 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ed8350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2119_batt53_1sess_005(self):
        """Poll 2026-02-24 21:19:03 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ed6350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2120_batt53_1sess_006(self):
        """Poll 2026-02-24 21:20:07 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ed4350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2121_batt53_1sess_007(self):
        """Poll 2026-02-24 21:21:10 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ed5350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2123_batt53_1sess_008(self):
        """Poll 2026-02-24 21:23:17 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ed3350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2124_batt53_1sess_009(self):
        """Poll 2026-02-24 21:24:20 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ed0350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2125_batt53_1sess_010(self):
        """Poll 2026-02-24 21:25:25 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ece350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2126_batt53_1sess_011(self):
        """Poll 2026-02-24 21:26:29 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ed7350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2129_batt53_1sess_012(self):
        """Poll 2026-02-24 21:29:39 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ed2350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2132_batt53_1sess_013(self):
        """Poll 2026-02-24 21:32:52 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ecf350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2136_batt53_1sess_014(self):
        """Poll 2026-02-24 21:36:02 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ec9350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2138_batt53_1sess_015(self):
        """Poll 2026-02-24 21:38:09 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ecd350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2142_batt53_1sess_016(self):
        """Poll 2026-02-24 21:42:23 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ecb350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2144_batt53_1sess_017(self):
        """Poll 2026-02-24 21:44:32 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ecc350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2146_batt53_1sess_018(self):
        """Poll 2026-02-24 21:46:43 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020eca350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2147_batt53_1sess_019(self):
        """Poll 2026-02-24 21:47:47 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ec8350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2154_batt53_1sess_020(self):
        """Poll 2026-02-24 21:54:44 – battery=53, 1 session(s) [2 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(53)
            .add_notification(bytes.fromhex('0303020ec7350000'))
            .add_notification(bytes.fromhex('03072a422300001a0217171d1d4c009600960805'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 53
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2156_batt45_1sess_021(self):
        """Poll 2026-02-24 21:56:10 – battery=45, 1 session(s) [4 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(45)
            .add_notification(bytes.fromhex('0303020ea72d0100'))
            .add_notification(bytes.fromhex('03072a422300011a02181535134c009600960b03'))
            .add_notification(bytes.fromhex('540000000f000823172208001111070f0f110000'))
            .add_notification(bytes.fromhex('5a00ffffffffffffff1a02180018134c00960096'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 45
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2157_batt45_1sess_022(self):
        """Poll 2026-02-24 21:57:16 – battery=45, 1 session(s) [4 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(45)
            .add_notification(bytes.fromhex('0303020eae2d0100'))
            .add_notification(bytes.fromhex('03072a422300011a02181535134c009600960b03'))
            .add_notification(bytes.fromhex('540000000f000823172208001111070f0f110000'))
            .add_notification(bytes.fromhex('5a00ffffffffffffff1a02180018134c00960096'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 45
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2158_batt45_1sess_023(self):
        """Poll 2026-02-24 21:58:20 – battery=45, 1 session(s) [4 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(45)
            .add_notification(bytes.fromhex('0303020ead2d0100'))
            .add_notification(bytes.fromhex('03072a422300011a02181535134c009600960b03'))
            .add_notification(bytes.fromhex('540000000f000823172208001111070f0f110000'))
            .add_notification(bytes.fromhex('5a00ffffffffffffff1a02180018134c00960096'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 45
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2200_batt45_1sess_024(self):
        """Poll 2026-02-24 22:00:28 – battery=45, 1 session(s) [4 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(45)
            .add_notification(bytes.fromhex('0303020eb22d0100'))
            .add_notification(bytes.fromhex('03072a422300011a02181535134c009600960b03'))
            .add_notification(bytes.fromhex('540000000f000823172208001111070f0f110000'))
            .add_notification(bytes.fromhex('5a00ffffffffffffff1a02180018134c00960096'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 45
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

    @pytest.mark.asyncio
    async def test_20260224_2201_batt45_1sess_025(self):
        """Poll 2026-02-24 22:01:31 – battery=45, 1 session(s) [4 notification(s)]"""
        client = (
            OcleanDeviceSimulator()
            .with_battery(45)
            .add_notification(bytes.fromhex('0303020eb02d0100'))
            .add_notification(bytes.fromhex('03072a422300011a02181535134c009600960b03'))
            .add_notification(bytes.fromhex('540000000f000823172208001111070f0f110000'))
            .add_notification(bytes.fromhex('5a00ffffffffffffff1a02180018134c00960096'))
            .build_client()
        )
        result = await _run_poll(_make_coordinator("AA:BB:CC:DD:EE:FF"), client)
        assert result.get("battery") == 45
        assert result.get("last_brush_time") is not None
        assert result.get("last_brush_duration") == 150
        assert result.get("last_brush_pnum") == 76

